### ISSUE TITLE
in lstm-crf-parallel.py the class BiLSTM_CRF_MODIFY_PARALLEL  is not used anywhere

### ISSUE THREAD

**Issue by vitaly-post** [mali19064/LSTM-CRF-pytorch-faster#1]
it seems that the class BiLSTM_CRF_MODIFY_PARALLEL  is not used anywhere

**Comment by GanjinZero** [comment]
This code uses
```
model = BiLSTM_CRF(len(word_to_ix), tag_to_ix, EMBEDDING_DIM, HIDDEN_DIM)
```

After you change the class name from BiLSTM_CRF_MODIFY_PARALLEL to BiLSTM_CRF, there still has a problem:
```
    model = BiLSTM_CRF(len(word_to_ix), tag_to_ix, EMBEDDING_DIM, HIDDEN_DIM)
TypeError: __init__() takes 4 positional arguments but 5 were given
```

**Comment by mali19064** [comment]
Thanks for your reminder, in the recent version, the problem is solved, you can try it again to make parallel training.
